name: fastapi-template
source: https://github.com/pyportion/fastapi-template
version: 1.0.1
description: A FastAPI Template.
author: PyPortion Team
type: fastapi

portions:
    - name: api
      steps:
          - type: ask
            question: What is the API name?
            variable: api_name

          - type: ask
            question: What is the router prefix?
            variable: router_prefix

          - type: set_var
            key: api_folder_name
            value: $api_name
            mode: snakecase

          - type: set_var
            key: router_file_name
            mode: snakecase
            value: $api_name

          - type: set_var
            key: registery_name
            mode: pascalcase
            value: $api_name
            suffix: Registry

          - type: create_folder
            path: ["app", "api", "$api_folder_name"]
            
          - type: copy
            from_path: ["api", "__init__.py"]
            to_path: ["app", "api", "$api_folder_name", "__init__.py"]

          - type: copy
            from_path: ["api", "router.py"]
            to_path: ["app", "api", "$api_folder_name", "$router_file_name"] 

          - type: replace
            path: ["app", "api", "$api_folder_name", "__init__.py"]
            replacements:
                - keyword: ROUTER_NAME
                  value: $router_file_name
                
                - keyword: ROUTER_PREFIX
                  value: router_prefix 

          - type: add_import
            path: ["app", "api", "__init__.py"]
            import_statement: "from .$api_folder_name import RoutersRegistry as $registery_name"

          - type: add_to_list
            path: ["app", "api", "__init__.py"]
            list_name: "routers"
            value: "$registery_name"
            as_identifier: True
